# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provider :libvirt do |kvm|
    kvm.memory = 8192
    kvm.cpus = 2
  end
#-------------------- mongo-0 --------------------#
  config.vm.define "mongo-0_192.168.33.30" do |server|
    server.vm.network "private_network", ip: "192.168.33.30"
    server.vm.hostname = "mongo-0"
    server.vm.provision "shell", privileged: true, inline: <<-SHELL
      sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
      sed -i -e 's/PasswordAuthentication\ no/PasswordAuthentication\ yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      echo "sudo ip link set eth1 mtu 1450" >> /etc/rc.local
      chmod u+x /etc/rc.d/rc.local
    SHELL
  end
#-------------------- mongo-1 --------------------#
  config.vm.define "mongo-1_192.168.33.31" do |server|
    server.vm.network "private_network", ip: "192.168.33.31"
    server.vm.hostname = "mongo-1"
    server.vm.provision "shell", privileged: true, inline: <<-SHELL
      sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
      sed -i -e 's/PasswordAuthentication\ no/PasswordAuthentication\ yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      echo "sudo ip link set eth1 mtu 1450" >> /etc/rc.local
      chmod u+x /etc/rc.d/rc.local
    SHELL
  end
#-------------------- mongo-2 --------------------#
  config.vm.define "mongo-2_192.168.33.32" do |server|
    server.vm.network "private_network", ip: "192.168.33.32"
    server.vm.hostname = "mongo-2"
    server.vm.provision "shell", privileged: true, inline: <<-SHELL
      sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
      sed -i -e 's/PasswordAuthentication\ no/PasswordAuthentication\ yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      echo "sudo ip link set eth1 mtu 1450" >> /etc/rc.local
      chmod u+x /etc/rc.d/rc.local
    SHELL
  end
#-------------------------------------------------#
end
